package neu.edu.entity;
// Generated 2017-12-12 23:58:19 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fundings generated by hbm2java
 */
@Entity
@Table(name = "fundings", catalog = "crowdfunding")
public class Fundings implements java.io.Serializable {

	private int fundId;
	private String date;
	private String ideaId;
	private String funderId;
	private String price;
	private String paymentMethod;

	public Fundings() {
	}

	public Fundings(int fundId) {
		this.fundId = fundId;
	}

	public Fundings(int fundId, String date, String ideaId, String funderId, String price, String paymentMethod) {
		this.fundId = fundId;
		this.date = date;
		this.ideaId = ideaId;
		this.funderId = funderId;
		this.price = price;
		this.paymentMethod = paymentMethod;
	}

	@Id

	@Column(name = "fund_id", unique = true, nullable = false)
	public int getFundId() {
		return this.fundId;
	}

	public void setFundId(int fundId) {
		this.fundId = fundId;
	}

	@Column(name = "date", length = 45)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "idea_id", length = 45)
	public String getIdeaId() {
		return this.ideaId;
	}

	public void setIdeaId(String ideaId) {
		this.ideaId = ideaId;
	}

	@Column(name = "funder_id", length = 45)
	public String getFunderId() {
		return this.funderId;
	}

	public void setFunderId(String funderId) {
		this.funderId = funderId;
	}

	@Column(name = "price", length = 45)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "payment_method", length = 45)
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

}
