package neu.edu.entity;
// Generated 2017-12-12 23:58:19 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "crowdfunding")
public class Project implements java.io.Serializable {

	private int id;
	private Byte companyid;
	private Byte serviceid;
	private Byte ideaid;
	private Byte iscompleted;
	private Integer progress;

	public Project() {
	}

	public Project(int id) {
		this.id = id;
	}

	public Project(int id, Byte companyid, Byte serviceid, Byte ideaid, Byte iscompleted, Integer progress) {
		this.id = id;
		this.companyid = companyid;
		this.serviceid = serviceid;
		this.ideaid = ideaid;
		this.iscompleted = iscompleted;
		this.progress = progress;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "companyid")
	public Byte getCompanyid() {
		return this.companyid;
	}

	public void setCompanyid(Byte companyid) {
		this.companyid = companyid;
	}

	@Column(name = "serviceid")
	public Byte getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(Byte serviceid) {
		this.serviceid = serviceid;
	}

	@Column(name = "ideaid")
	public Byte getIdeaid() {
		return this.ideaid;
	}

	public void setIdeaid(Byte ideaid) {
		this.ideaid = ideaid;
	}

	@Column(name = "iscompleted")
	public Byte getIscompleted() {
		return this.iscompleted;
	}

	public void setIscompleted(Byte iscompleted) {
		this.iscompleted = iscompleted;
	}

	@Column(name = "progress")
	public Integer getProgress() {
		return this.progress;
	}

	public void setProgress(Integer progress) {
		this.progress = progress;
	}

}
