package neu.edu.entity;
// Generated 2017-12-12 23:58:19 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "crowdfunding")
public class Role implements java.io.Serializable {

	private int roleid;
	private String roleName;
	private String description;

	public Role() {
	}

	public Role(int roleid) {
		this.roleid = roleid;
	}

	public Role(int roleid, String roleName, String description) {
		this.roleid = roleid;
		this.roleName = roleName;
		this.description = description;
	}

	@Id

	@Column(name = "roleid", unique = true, nullable = false)
	public int getRoleid() {
		return this.roleid;
	}

	public void setRoleid(int roleid) {
		this.roleid = roleid;
	}

	@Column(name = "role_name", length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
