package neu.edu.entity;
// Generated 2017-12-12 23:58:19 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Starupservice generated by hbm2java
 */
@Entity
@Table(name = "starupservice", catalog = "crowdfunding")
public class Starupservice implements java.io.Serializable {

	private int serviceId;
	private Integer starupId;
	private String category;
	private String des;
	private String price;

	public Starupservice() {
	}

	public Starupservice(int serviceId) {
		this.serviceId = serviceId;
	}

	public Starupservice(int serviceId, Integer starupId, String category, String des, String price) {
		this.serviceId = serviceId;
		this.starupId = starupId;
		this.category = category;
		this.des = des;
		this.price = price;
	}

	@Id

	@Column(name = "service_id", unique = true, nullable = false)
	public int getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "starup_id")
	public Integer getStarupId() {
		return this.starupId;
	}

	public void setStarupId(Integer starupId) {
		this.starupId = starupId;
	}

	@Column(name = "category", length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "des", length = 45)
	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

	@Column(name = "price", length = 45)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

}
