package neu.edu.entity;
// Generated 2017-12-12 23:58:19 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "crowdfunding")
public class User implements java.io.Serializable {

	private int userId;
	private String username;
	private String password;
	private String email;
	private Integer roleId;
	private Byte isActived;
	private String reason;

	public User() {
	}

	public User(int userId) {
		this.userId = userId;
	}

	public User(int userId, String username, String password, String email, Integer roleId, Byte isActived,
			String reason) {
		this.userId = userId;
		this.username = username;
		this.password = password;
		this.email = email;
		this.roleId = roleId;
		this.isActived = isActived;
		this.reason = reason;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "role_id")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "is_actived")
	public Byte getIsActived() {
		return this.isActived;
	}

	public void setIsActived(Byte isActived) {
		this.isActived = isActived;
	}

	@Column(name = "reason", length = 1000)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
