package neu.edu.entity;
// Generated Nov 6, 2017 11:26:29 PM by Hibernate Tools 5.1.4.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address")
public class Address implements java.io.Serializable {

	private AddressId id;
	private Person person;
	private String address;
	private Integer zip;

	public Address() {
	}

	public Address(AddressId id, Person person) {
		this.id = id;
		this.person = person;
	}

	public Address(AddressId id, Person person, String address, Integer zip) {
		this.id = id;
		this.person = person;
		this.address = address;
		this.zip = zip;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "personId", column = @Column(name = "person_id", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "type", nullable = false, length = 45)) })
	public AddressId getId() {
		return this.id;
	}

	public void setId(AddressId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person_id", nullable = false, insertable = false, updatable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "zip")
	public Integer getZip() {
		return this.zip;
	}

	public void setZip(Integer zip) {
		this.zip = zip;
	}

}
