package neu.edu.entity;
// Generated Nov 6, 2017 11:26:29 PM by Hibernate Tools 5.1.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AddressId generated by hbm2java
 */
@Embeddable
public class AddressId implements java.io.Serializable {

	private int personId;
	private String type;

	public AddressId() {
	}

	public AddressId(int personId, String type) {
		this.personId = personId;
		this.type = type;
	}

	@Column(name = "person_id", nullable = false)
	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AddressId))
			return false;
		AddressId castOther = (AddressId) other;

		return (this.getPersonId() == castOther.getPersonId())
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPersonId();
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		return result;
	}

}
