package neu.edu.entity;
// Generated 2017-12-14 14:57:06 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Idea generated by hbm2java
 */
@Entity
@Table(name = "idea")
public class Idea implements java.io.Serializable {

	private int id;
	private Integer userId;
	private String name;
	private String des;
	private String createDate;
	private String category;
	private String duration;
	private Integer totalFunding;
	private Integer price;
	private Integer pieceRemain;
	private String isActived;
	private String reson;
	private String endDate;
	private Integer pieceGet;

	public Idea() {
	}

	public Idea(int id) {
		this.id = id;
	}

	public Idea(int id, Integer userId, String name, String des, String createDate, String category, String duration,
			Integer totalFunding, Integer price, Integer pieceRemain, String isActived, String reson, String endDate,
			Integer pieceGet) {
		this.id = id;
		this.userId = userId;
		this.name = name;
		this.des = des;
		this.createDate = createDate;
		this.category = category;
		this.duration = duration;
		this.totalFunding = totalFunding;
		this.price = price;
		this.pieceRemain = pieceRemain;
		this.isActived = isActived;
		this.reson = reson;
		this.endDate = endDate;
		this.pieceGet = pieceGet;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "des", length = 45)
	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

	@Column(name = "create_date", length = 45)
	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	@Column(name = "category", length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "duration", length = 45)
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "total_funding")
	public Integer getTotalFunding() {
		return this.totalFunding;
	}

	public void setTotalFunding(Integer totalFunding) {
		this.totalFunding = totalFunding;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "piece_remain")
	public Integer getPieceRemain() {
		return this.pieceRemain;
	}

	public void setPieceRemain(Integer pieceRemain) {
		this.pieceRemain = pieceRemain;
	}

	@Column(name = "is_actived", length = 45)
	public String getIsActived() {
		return this.isActived;
	}

	public void setIsActived(String isActived) {
		this.isActived = isActived;
	}

	@Column(name = "reson", length = 45)
	public String getReson() {
		return this.reson;
	}

	public void setReson(String reson) {
		this.reson = reson;
	}

	@Column(name = "end_date", length = 45)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Column(name = "piece_get")
	public Integer getPieceGet() {
		return this.pieceGet;
	}

	public void setPieceGet(Integer pieceGet) {
		this.pieceGet = pieceGet;
	}

}
