package neu.edu.entity;
// Generated 2017-12-14 14:57:06 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project")
public class Project implements java.io.Serializable {

	private int id;
	private Integer companyid;
	private Integer serviceid;
	private Integer ideaid;
	private String iscompleted;
	private Integer progress;

	public Project() {
	}

	public Project(int id) {
		this.id = id;
	}

	public Project(int id, Integer companyid, Integer serviceid, Integer ideaid, String iscompleted, Integer progress) {
		this.id = id;
		this.companyid = companyid;
		this.serviceid = serviceid;
		this.ideaid = ideaid;
		this.iscompleted = iscompleted;
		this.progress = progress;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "companyid")
	public Integer getCompanyid() {
		return this.companyid;
	}

	public void setCompanyid(Integer companyid) {
		this.companyid = companyid;
	}

	@Column(name = "serviceid")
	public Integer getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(Integer serviceid) {
		this.serviceid = serviceid;
	}

	@Column(name = "ideaid")
	public Integer getIdeaid() {
		return this.ideaid;
	}

	public void setIdeaid(Integer ideaid) {
		this.ideaid = ideaid;
	}

	@Column(name = "iscompleted", length = 45)
	public String getIscompleted() {
		return this.iscompleted;
	}

	public void setIscompleted(String iscompleted) {
		this.iscompleted = iscompleted;
	}

	@Column(name = "progress")
	public Integer getProgress() {
		return this.progress;
	}

	public void setProgress(Integer progress) {
		this.progress = progress;
	}

}
