package neu.edu.entity;
// Generated 2017-12-15 9:37:33 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Startupservice generated by hbm2java
 */
@Entity
@Table(name = "startupservice")
public class Startupservice implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int serviceId;
	private Integer startupId;
	private String category;
	private String des;
	private Integer price;
	private String isAvailable;
	private String reason;

	public Startupservice() {
	}

	public Startupservice(int serviceId) {
		this.serviceId = serviceId;
	}

	public Startupservice(int serviceId, Integer startupId, String category, String des, Integer price,
			String isAvailable, String reason) {
		this.serviceId = serviceId;
		this.startupId = startupId;
		this.category = category;
		this.des = des;
		this.price = price;
		this.isAvailable = isAvailable;
		this.reason = reason;
	}

	@Id

	@Column(name = "service_id", unique = true, nullable = false)
	public int getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "startup_id")
	public Integer getStartupId() {
		return this.startupId;
	}

	public void setStartupId(Integer startupId) {
		this.startupId = startupId;
	}

	@Column(name = "category", length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "des", length = 45)
	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "is_available", length = 45)
	public String getIsAvailable() {
		return this.isAvailable;
	}

	public void setIsAvailable(String isAvailable) {
		this.isAvailable = isAvailable;
	}

	@Column(name = "reason", length = 45)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
