package neu.edu.other;
// Generated 2017-12-15 9:37:33 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "DemoApp")
public class Address implements java.io.Serializable {

	private AddressId id;
	private String address;
	private Integer zip;

	public Address() {
	}

	public Address(AddressId id) {
		this.id = id;
	}

	public Address(AddressId id, String address, Integer zip) {
		this.id = id;
		this.address = address;
		this.zip = zip;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "personId", column = @Column(name = "person_id", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "type", nullable = false, length = 45)) })
	public AddressId getId() {
		return this.id;
	}

	public void setId(AddressId id) {
		this.id = id;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "zip")
	public Integer getZip() {
		return this.zip;
	}

	public void setZip(Integer zip) {
		this.zip = zip;
	}

}
