package neu.edu.other;
// Generated 2017-12-15 9:37:33 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ideaservice generated by hbm2java
 */
@Entity
@Table(name = "ideaservice", catalog = "DemoApp")
public class Ideaservice implements java.io.Serializable {

	private int id;
	private Integer ideaId;
	private String category;
	private String startDate;
	private String endDate;
	private String duration;
	private String des;
	private String price;
	private String isActivated;
	private String reason;

	public Ideaservice() {
	}

	public Ideaservice(int id) {
		this.id = id;
	}

	public Ideaservice(int id, Integer ideaId, String category, String startDate, String endDate, String duration,
			String des, String price, String isActivated, String reason) {
		this.id = id;
		this.ideaId = ideaId;
		this.category = category;
		this.startDate = startDate;
		this.endDate = endDate;
		this.duration = duration;
		this.des = des;
		this.price = price;
		this.isActivated = isActivated;
		this.reason = reason;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "idea_id")
	public Integer getIdeaId() {
		return this.ideaId;
	}

	public void setIdeaId(Integer ideaId) {
		this.ideaId = ideaId;
	}

	@Column(name = "category", length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "start_date", length = 45)
	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	@Column(name = "end_date", length = 45)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Column(name = "duration", length = 45)
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "des", length = 45)
	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

	@Column(name = "price", length = 45)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "is_activated", length = 45)
	public String getIsActivated() {
		return this.isActivated;
	}

	public void setIsActivated(String isActivated) {
		this.isActivated = isActivated;
	}

	@Column(name = "reason", length = 45)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
