package neu.edu.other;
// Generated 2017-12-15 9:37:33 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "DemoApp")
public class Location implements java.io.Serializable {

	private String region;
	private String location;

	public Location() {
	}

	public Location(String region) {
		this.region = region;
	}

	public Location(String region, String location) {
		this.region = region;
		this.location = location;
	}

	@Id

	@Column(name = "region", unique = true, nullable = false, length = 45)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "location", length = 10000)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

}
